export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS__PENDING'
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS__SUCCESS'
export const REQUEST_PRODUCTS_FAILED = 'REQUEST_PRODUCTS__FAILED'